### ISSUE TITLE
Tables without primary keys

### ISSUE THREAD

**Issue by germain-italic** [jan-vandenberg/cruddiy#79]
In PR #74 
- Fixed some issues with default orderby / groupby
- Disabled broken Action buttons

**Before:**

![](https://files.italic.fr/chrome_vpX20I6M8I.png)

**After:**

![](https://files.italic.fr/chrome_POBMc4ztB8.png)

**Comment by jan-vandenberg** [comment]
So this is fixed now?

**Comment by germain-italic** [comment]
The issue is catched properly as there is no more error message and unusable buttons.

However, it's not fixed (actions are not available).

To fix, one must change the forced parameter $column_id (which is set to primary key) when there is none, and use a where on all the columns.

It's not in my plans in the near future.

**Comment by germain-italic** [comment]
Following #122, it is acknowledged that the export doesn't work tor tables without PK or a non-numerical PK.
